export const tableData = [{
 "AP": "3.6",
 "CPV": "0.0005",
 "CR": "0.005885",
 "CTR": "0.03514",
 "CV": "0.000207",
 "Clicks": "3908",
 "Conversion Cap": "",
 "Conversions": "23",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "58.5937",
 "Country": "United Kingdom",
 "EPC": "0.0212",
 "EPV": "0.0007",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "24.2063",
 "ROI": "0.413121",
 "Revenue": "82.8",
 "Visits": "111212"
},{
 "AP": "3.6",
 "CPV": "0.0005",
 "CR": "0.008153",
 "CTR": "0.030083",
 "CV": "0.000245",
 "Clicks": "2821",
 "Conversion Cap": "",
 "Conversions": "23",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "49.5621",
 "Country": "United Kingdom",
 "EPC": "0.0294",
 "EPV": "0.0009",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "33.2379",
 "ROI": "0.670633",
 "Revenue": "82.8",
 "Visits": "93773"
},{
 "AP": "3.5071",
 "CPV": "0.0005",
 "CR": "0.006298",
 "CTR": "0.03144",
 "CV": "0.000198",
 "Clicks": "2223",
 "Conversion Cap": "600",
 "Conversions": "14",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "36.9891",
 "Country": "United Kingdom",
 "EPC": "0.0221",
 "EPV": "0.0007",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "12.1109",
 "ROI": "0.327417",
 "Revenue": "49.1",
 "Visits": "70707"
},{
 "AP": "3.2",
 "CPV": "0.0005",
 "CR": "0.00432",
 "CTR": "0.026877",
 "CV": "0.000116",
 "Clicks": "1389",
 "Conversion Cap": "",
 "Conversions": "6",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "27.3246",
 "Country": "United Kingdom",
 "EPC": "0.0138",
 "EPV": "0.0004",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-8.1246",
 "ROI": "-0.297337",
 "Revenue": "19.2",
 "Visits": "51680"
},{
 "AP": "3.52",
 "CPV": "0.0005",
 "CR": "0.007924",
 "CTR": "0.025185",
 "CV": "0.0002",
 "Clicks": "631",
 "Conversion Cap": "600",
 "Conversions": "5",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "12.9047",
 "Country": "United Kingdom",
 "EPC": "0.0279",
 "EPV": "0.0007",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "4.6953",
 "ROI": "0.363843",
 "Revenue": "17.6",
 "Visits": "25055"
},{
 "AP": "3.6",
 "CPV": "0.0005",
 "CR": "0.000986",
 "CTR": "0.108746",
 "CV": "0.000107",
 "Clicks": "2028",
 "Conversion Cap": "",
 "Conversions": "2",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "10.1163",
 "Country": "United Kingdom",
 "EPC": "0.0036",
 "EPV": "0.0004",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-2.9163",
 "ROI": "-0.288278",
 "Revenue": "7.2",
 "Visits": "18649"
},{
 "AP": "3.5",
 "CPV": "0.0005",
 "CR": "0.005671",
 "CTR": "0.032238",
 "CV": "0.000183",
 "Clicks": "529",
 "Conversion Cap": "600",
 "Conversions": "3",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "7.7407",
 "Country": "United Kingdom",
 "EPC": "0.0198",
 "EPV": "0.0006",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "2.7593",
 "ROI": "0.356459",
 "Revenue": "10.5",
 "Visits": "16409"
},{
 "AP": "3.2",
 "CPV": "0.0005",
 "CR": "0.00678",
 "CTR": "0.0237",
 "CV": "0.000161",
 "Clicks": "295",
 "Conversion Cap": "",
 "Conversions": "2",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "6.7482",
 "Country": "United Kingdom",
 "EPC": "0.0217",
 "EPV": "0.0005",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.3482",
 "ROI": "-0.051603",
 "Revenue": "6.4",
 "Visits": "12447"
},{
 "AP": "3.2",
 "CPV": "0.0005",
 "CR": "0.008403",
 "CTR": "0.020537",
 "CV": "0.000173",
 "Clicks": "238",
 "Conversion Cap": "",
 "Conversions": "2",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "5.5917",
 "Country": "United Kingdom",
 "EPC": "0.0269",
 "EPV": "0.0006",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "0.8083",
 "ROI": "0.14456",
 "Revenue": "6.4",
 "Visits": "11589"
},{
 "AP": "3.6",
 "CPV": "0.0005",
 "CR": "0.008368",
 "CTR": "0.021713",
 "CV": "0.000182",
 "Clicks": "239",
 "Conversion Cap": "",
 "Conversions": "2",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "5.2429",
 "Country": "United Kingdom",
 "EPC": "0.0301",
 "EPV": "0.0007",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "1.9571",
 "ROI": "0.373278",
 "Revenue": "7.2",
 "Visits": "11007"
},{
 "AP": "3.55",
 "CPV": "0.0005",
 "CR": "0.010811",
 "CTR": "0.017654",
 "CV": "0.000191",
 "Clicks": "185",
 "Conversion Cap": "600",
 "Conversions": "2",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "4.953",
 "Country": "United Kingdom",
 "EPC": "0.0384",
 "EPV": "0.0007",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "2.147",
 "ROI": "0.433486",
 "Revenue": "7.1",
 "Visits": "10479"
},{
 "AP": "3.2",
 "CPV": "0.0005",
 "CR": "0.004902",
 "CTR": "0.019762",
 "CV": "0.000097",
 "Clicks": "204",
 "Conversion Cap": "",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "4.9131",
 "Country": "United Kingdom",
 "EPC": "0.0157",
 "EPV": "0.0003",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-1.7131",
 "ROI": "-0.348679",
 "Revenue": "3.2",
 "Visits": "10323"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.021745",
 "CV": "0",
 "Clicks": "223",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "4.7787",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-4.7787",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "10255"
},{
 "AP": "2",
 "CPV": "0.0005",
 "CR": "0.006024",
 "CTR": "0.022834",
 "CV": "0.000138",
 "Clicks": "166",
 "Conversion Cap": "",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "3.529",
 "Country": "United Kingdom",
 "EPC": "0.012",
 "EPV": "0.0003",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-1.529",
 "ROI": "-0.433264",
 "Revenue": "2",
 "Visits": "7270"
},{
 "AP": "2",
 "CPV": "0.0005",
 "CR": "0.004587",
 "CTR": "0.03009",
 "CV": "0.000138",
 "Clicks": "218",
 "Conversion Cap": "",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "3.5111",
 "Country": "United Kingdom",
 "EPC": "0.0092",
 "EPV": "0.0003",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-1.5111",
 "ROI": "-0.430381",
 "Revenue": "2",
 "Visits": "7245"
},{
 "AP": "2",
 "CPV": "0.0005",
 "CR": "0.002801",
 "CTR": "0.049439",
 "CV": "0.000138",
 "Clicks": "357",
 "Conversion Cap": "",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "3.4904",
 "Country": "United Kingdom",
 "EPC": "0.0056",
 "EPV": "0.0003",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-1.4904",
 "ROI": "-0.427",
 "Revenue": "2",
 "Visits": "7221"
},{
 "AP": "2.5",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0.000145",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "3.6482",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0.0004",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - CPL SMARTLINK BADOO (INDEX)",
 "Profit": "-1.1482",
 "ROI": "-0.314722",
 "Revenue": "2.5",
 "Visits": "6878"
},{
 "AP": "2.5",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0.000469",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "2",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "1.9444",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0.0012",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - CPL POP 4  BADOO (pop)",
 "Profit": "3.0556",
 "ROI": "1.57143",
 "Revenue": "5",
 "Visits": "4267"
},{
 "AP": "2.5",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0.000254",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "1.77",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0.0006",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - BADOO TOP ROOM",
 "Profit": "0.73",
 "ROI": "0.412463",
 "Revenue": "2.5",
 "Visits": "3930"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.033788",
 "CV": "0",
 "Clicks": "104",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "1.6676",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (lollipop)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-1.6676",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "3078"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "1.6681",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - CPL SMARTLINK BADOO",
 "Profit": "-1.6681",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "2763"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.028703",
 "CV": "0",
 "Clicks": "75",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "1.3792",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (lollipop)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-1.3792",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "2613"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.9686",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - BADOO FREE TOKENS",
 "Profit": "-0.9686",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "2210"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.9993",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - CPL POP 3  BADOO (pop)",
 "Profit": "-0.9993",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "2173"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.949",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - BADOO Land variation",
 "Profit": "-0.949",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "2115"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.060886",
 "CV": "0",
 "Clicks": "99",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.8858",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.8858",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1626"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.024142",
 "CV": "0",
 "Clicks": "38",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.8121",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (lollipop)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.8121",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1574"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.035415",
 "CV": "0",
 "Clicks": "55",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.8037",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (English tea)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.8037",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1553"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.022",
 "CV": "0",
 "Clicks": "33",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.7913",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (English tea)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.7913",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1500"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.022252",
 "CV": "0",
 "Clicks": "33",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.7533",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (English tea)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.7533",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1483"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.045356",
 "CV": "0",
 "Clicks": "63",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.7756",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.7756",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1389"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.203376",
 "CV": "0",
 "Clicks": "253",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.6319",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.6319",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1244"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.039421",
 "CV": "0",
 "Clicks": "49",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.7029",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.7029",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1243"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.159643",
 "CV": "0",
 "Clicks": "197",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.6528",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.6528",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "1234"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.04883",
 "CV": "0",
 "Clicks": "48",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.5623",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.5623",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "983"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.033746",
 "CV": "0",
 "Clicks": "30",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.4404",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.4404",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "889"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.050076",
 "CV": "0",
 "Clicks": "33",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.3661",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.3661",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "659"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.033123",
 "CV": "0",
 "Clicks": "21",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.3318",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.3318",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "634"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.021622",
 "CV": "0",
 "Clicks": "12",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.285",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "clickdealer - Global - (49890) [WEB+MOB] CindyMatches - SOI - US/UK/CA/AU/NZ/IE",
 "Profit": "-0.285",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "555"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.037523",
 "CV": "0",
 "Clicks": "20",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.2657",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "clickdealer - Global - (49890) [WEB+MOB] CindyMatches - SOI - US/UK/CA/AU/NZ/IE",
 "Profit": "-0.2657",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "533"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.018367",
 "CV": "0",
 "Clicks": "9",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.252",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.252",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "490"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.041667",
 "CV": "0",
 "Clicks": "20",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.2485",
 "Country": "United Kingdom",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "clickdealer - Global - (49890) [WEB+MOB] CindyMatches - SOI - US/UK/CA/AU/NZ/IE",
 "Profit": "-0.2485",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "480"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.008511",
 "CV": "0",
 "Clicks": "4",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.2386",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.2386",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "470"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.006494",
 "CV": "0",
 "Clicks": "3",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.2502",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.2502",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "462"
},{
 "AP": "3.5",
 "CPV": "0.0006",
 "CR": "0.034483",
 "CTR": "0.074359",
 "CV": "0.002564",
 "Clicks": "29",
 "Conversion Cap": "600",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.2199",
 "Country": "Germany",
 "EPC": "0.1207",
 "EPV": "0.009",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "3.2801",
 "ROI": "14.91944",
 "Revenue": "3.5",
 "Visits": "390"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.061889",
 "CV": "0",
 "Clicks": "19",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.1693",
 "Country": "France",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.1693",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "307"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.018797",
 "CV": "0",
 "Clicks": "5",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.1356",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.1356",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "266"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.037879",
 "CV": "0",
 "Clicks": "10",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.1521",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.1521",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "264"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.049618",
 "CV": "0",
 "Clicks": "13",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.1563",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.1563",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "262"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.095238",
 "CV": "0",
 "Clicks": "22",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.1351",
 "Country": "France",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.1351",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "231"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.035874",
 "CV": "0",
 "Clicks": "8",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.1129",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.1129",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "223"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.008969",
 "CV": "0",
 "Clicks": "2",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.1193",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.1193",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "223"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.009615",
 "CV": "0",
 "Clicks": "2",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.1107",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.1107",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "208"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.065089",
 "CV": "0",
 "Clicks": "11",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0955",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0955",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "169"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.006024",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0968",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0968",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "166"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.048485",
 "CV": "0",
 "Clicks": "8",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0855",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0855",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "165"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.006536",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0815",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0815",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "153"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.04",
 "CV": "0",
 "Clicks": "6",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0822",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0822",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "150"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.006849",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0811",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0811",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "146"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.028369",
 "CV": "0",
 "Clicks": "4",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0799",
 "Country": "France",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0799",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "141"
},{
 "AP": "3.5",
 "CPV": "0.0005",
 "CR": "0.166667",
 "CTR": "0.043165",
 "CV": "0.007194",
 "Clicks": "6",
 "Conversion Cap": "600",
 "Conversions": "1",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0707",
 "Country": "Germany",
 "EPC": "0.5833",
 "EPV": "0.0252",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "3.4293",
 "ROI": "48.521788",
 "Revenue": "3.5",
 "Visits": "139"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.066176",
 "CV": "0",
 "Clicks": "9",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.078",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.078",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "136"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.014706",
 "CV": "0",
 "Clicks": "2",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0811",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0811",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "136"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.015504",
 "CV": "0",
 "Clicks": "2",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0707",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0707",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "129"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.033898",
 "CV": "0",
 "Clicks": "4",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.064",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.064",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "118"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.063",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.063",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "112"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.027027",
 "CV": "0",
 "Clicks": "3",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0653",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0653",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "111"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.037383",
 "CV": "0",
 "Clicks": "4",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0562",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0562",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "107"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.057143",
 "CV": "0",
 "Clicks": "6",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0513",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-0.0513",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "105"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.069307",
 "CV": "0",
 "Clicks": "7",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0577",
 "Country": "France",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0577",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "101"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.020619",
 "CV": "0",
 "Clicks": "2",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.046",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-0.046",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "97"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.073684",
 "CV": "0",
 "Clicks": "7",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0486",
 "Country": "Libya",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0486",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "95"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.042105",
 "CV": "0",
 "Clicks": "4",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0475",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-0.0475",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "95"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0.064516",
 "CV": "0",
 "Clicks": "6",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0372",
 "Country": "Turkey",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0372",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "93"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.010753",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0485",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0485",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "93"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.086957",
 "CV": "0",
 "Clicks": "8",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0488",
 "Country": "Libya",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0488",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "92"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.034483",
 "CV": "0",
 "Clicks": "3",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0413",
 "Country": "Libya",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0413",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "87"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0358",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - CPL SMARTLINK BADOO (INDEX)",
 "Profit": "-0.0358",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "75"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0.014085",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0312",
 "Country": "Turkey",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0312",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "71"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0.048387",
 "CV": "0",
 "Clicks": "3",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0272",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-0.0272",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "62"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.016129",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.028",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-0.028",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "62"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0.080645",
 "CV": "0",
 "Clicks": "5",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.025",
 "Country": "Turkey",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.025",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "62"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.016393",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0308",
 "Country": "Libya",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0308",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "61"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0313",
 "Country": "Portugal",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0313",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "61"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0233",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - CPL POP 4  BADOO (pop)",
 "Profit": "-0.0233",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "59"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0291",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0291",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "58"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0.087719",
 "CV": "0",
 "Clicks": "5",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0337",
 "Country": "France",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chat bear)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0337",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "57"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0319",
 "Country": "Netherlands",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "Direct linking",
 "Offer": "Global - CPL SMARTLINK BADOO (INDEX)",
 "Profit": "-0.0319",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "57"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0232",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0232",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "56"
},{
 "AP": "0",
 "CPV": "0.0007",
 "CR": "0",
 "CTR": "0.057692",
 "CV": "0",
 "Clicks": "3",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0379",
 "Country": "Saudi Arabia",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0379",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "52"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0285",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0285",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "51"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0255",
 "Country": "China",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0255",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "50"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0237",
 "Country": "France",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0237",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "50"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0221",
 "Country": "Portugal",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0221",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "50"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0313",
 "Country": "China",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (B/W jumper_2)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0313",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "49"
},{
 "AP": "0",
 "CPV": "0.0006",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0274",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (chris on the bottom)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0274",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "49"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0.021277",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "600",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "0",
 "Cost": "0.0256",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "United Kingdom - ||AV|| [UK] [MOB-TAB-WEB] [950] - Second Fling | DOI | UK (uk-mob)",
 "Profit": "-0.0256",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "47"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0226",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - ||AV || [US, UK, CA, AU] [TAB+MOB] || Spdate | SOI ",
 "Profit": "-0.0226",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "46"
},{
 "AP": "0",
 "CPV": "0.0004",
 "CR": "0",
 "CTR": "0.022727",
 "CV": "0",
 "Clicks": "1",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0191",
 "Country": "Germany",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (jumper_1)",
 "Offer": "United Kingdom - CD - [MOB] [56421] CHEEKYLOVERS /UK SOI quarter",
 "Profit": "-0.0191",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "44"
},{
 "AP": "0",
 "CPV": "0.0005",
 "CR": "0",
 "CTR": "0",
 "CV": "0",
 "Clicks": "0",
 "Conversion Cap": "",
 "Conversions": "0",
 "Conversions as Counted for Conversion Cap": "",
 "Cost": "0.0232",
 "Country": "United States",
 "EPC": "0",
 "EPV": "0",
 "Errors": "0",
 "Lander": "United Kingdom - MOB - (red alert)",
 "Offer": "Global - CD - [UK] [AU] [NZ] [WEB+MOB] [53069] WHITECHRISTIANHATE",
 "Profit": "-0.0232",
 "ROI": "-1",
 "Revenue": "0",
 "Visits": "44"
}];